name: Scrape AmiAmi Sales

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (adjust as needed)
  workflow_dispatch:       # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run scraper
      run: |
        python amiami-sales.py

    - name: Commit and push CSV
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add AmiAmi_sales.csv
        git commit -m "Auto-update CSV" || echo "No changes"
        git push
